---
- hosts: all

  vars:
    homebrew_user: nicholas.the.personal
    homebrew_group: admin
    homebrew_upgrade_all_packages: true

  tasks:
    - name: Let me check your password first
      command: echo "Password test in progress..."
      timeout: 1
      become: true
      changed_when: false

    - debug:
        msg: Hello, World!

    - name: Check if the dotfile repo is there
      stat:
        path: ~/.git/
      register: dotfile_repo

    - name: Clone the dotfile repo into the home directory `~`
      shell: |
        cd ~
        git init
        git remote add origin https://github.com/NicholasTD07/dotfiles.git
        git fetch origin
        git checkout -b main origin/main
      when: not dotfile_repo.stat.exists

    - name: Update the dotfile repo
      git:
        repo: https://github.com/NicholasTD07/dotfiles.git
        dest: ~/
        version: main
      when: dotfile_repo.stat.exists

    - name: Set up Homebrew (and upgrade all packages)
      include_role:
        name: geerlingguy.mac.homebrew

    # Because Spacemacs takes so long to finish its initial bootstrap,
    # let's do it as early as we can.
    - name: Tap the Emacs Plus repository
      homebrew_tap:
        name: d12frosted/emacs-plus

    # Not sure whether libvterm is needed here...
    - name: Install Emacs Plus
      homebrew:
        name: "{{ item }}"
      loop:
        - emacs-plus
        - libvterm # Is this needed though?

    - name: Symlink the Emacs.app to /Applications
      file:
        src: /opt/homebrew/opt/emacs-plus/Emacs.app
        dest: /Applications/Emacs.app
        state: link

    - name: Check if Spacemacs has been initialized
      stat:
        path: ~/.emacs.d/
      register: spacemacs_stat

    - name: Bootstrap Spacemacs if it hasn't been initialized yet
      block:
        - name: Clone Spacemacs into the ~/.emacs.d directory
          git:
            repo: https://github.com/syl20bnr/spacemacs.git
            dest: ~/.emacs.d/
            version: develop

        - command: emacs &
          async: 600 # Give Emacs 10 minutes to run
          poll: 0 # in the background
      when: not spacemacs_stat.stat.exists

    - name: Install Vim
      homebrew:
        name: "{{ item }}"
      loop:
        - vim
        - cmake # needed by YouCompleteMe

    - name: Check if Vim plugins are installed
      stat:
        path: ~/.vim-plugins/
      register: vim_plugins_stat

    - name: Bootstrap Vim plugins if plugins are not installed yet
      command: vim
      async: 90 # Give Vim one minute and half to run
      poll: 0 # in the background
      when: not vim_plugins_stat.stat.exists

    # Caveat: Due to the nature of how Vim and its plugins are installed,
    # YouCompleteMe won't be installed on the first run of the playbook...

    - name: Check if YouCompleteMe has been compiled
      stat:
        path: ~/.vim-plugins/plugins/YouCompleteMe/.compiled
      register: YCM_compiled

    - name: Compile YouCompleteMe
      block:
      - name: Compile YouCompleteMe
        command:
          cmd: python3 install.py
          chdir: ~/.vim-plugins/plugins/YouCompleteMe

      - name: Mark YCM as compiled
        file:
          path: ~/.vim-plugins/plugins/YouCompleteMe/.compiled
          state: touch
      when: vim_plugins_stat.stat.exists and not YCM_compiled.stat.exists

    - name: Tap the fonts repository
      homebrew_tap:
        name: homebrew/cask-fonts

    - name: Install Homebrew packages
      homebrew:
        name: "{{ item }}"
        state: present
      loop:
        # commandline utilities
        - fish
        - tree

        # git
        - git
        - git-lfs
        - ydiff # needed by git for diffing

        # editors support
        - fzf # needed by fish and also vim for searching

        - ripgrep # needed by emacs for searching
        - ispell # needed by emacs for spell checks

        # languages
        - python
        - rbenv

        # Swift

        - carthage # Until SPM solves its binary caches on CI, carthage is our friend...

        - swiftlint
        - swiftformat

        # misc
        - svn # need by the font casks

    - name: Install Homebrew Casks
      homebrew_cask:
        name: "{{ item }}"
        state: present
      loop:
        # macOS must-haves
        - 1password
        - dropbox
        - firefox
        # - little-snitch

        # work / life?
        - zoom
        - slack # needed for the huddles

        # macOS quality of life improvements
        - alfred
        - bartender
        - caffeine
        - istat-menus
        - iterm2
        - moom

        # gaming
        - steam

        # streaming
        - obs
        - loopback

        # MIA
        # mas 'DaisyDisk', id: 411643860
        # mas 'GIPHY CAPTURE', id: 668208984
        # mas 'Disk Care', id: 913724705

    - name: Install Homebrew Font Casks (that can be shared with other users)
      homebrew_cask:
        name: "{{ item }}"
        state: present
        install_options:
          - 'fontdir=/Users/Shared/Fonts'
      loop:
        # fonts
        - font-inconsolata-g-for-powerline
        - font-source-code-pro
        - font-source-code-pro-for-powerline

    - name: Install the fonts
      copy:
        src: "{{ item  }}"
        dest: ~/Library/Fonts
      with_fileglob:
        - /Users/Shared/Fonts/*

    - name: Ensure Ansible is installed with Homebrew's pip
      pip:
        name: ansible
      vars:
        extra_path: /opt/homebrew/bin
